### ISSUE TITLE
ERROR: Getting to reward website failed, retrying...

### ISSUE THREAD

**Issue by Sato-Isolated** [Yudaotor/EsportsHelper#107]
I get this message every time 

`
League: LEC Viewers: 58179 Definition: 160p
Title: G2 VS. RGE  0 - 0 (1/BESTOF 1)
2024-01-15 17:59:27,225 INFO: Next check at: 01-15 18:07:27
2024-01-15 17:59:27,225 INFO: ==================================================
2024-01-15 18:07:28,247 INFO: Start checking...
2024-01-15 18:07:28,714 INFO: Checking live broadcasts...
2024-01-15 18:07:29,127 INFO: Checking drops number...
2024-01-15 18:08:35,366 INFO: rewardError-Debug screenshot successful.
2024-01-15 18:08:51,228 ERROR: Getting to reward website failed, retrying...
2024-01-15 18:08:51,229 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "C:\Users\ismys\Documents\GitHub\EsportsHelper\EsportsHelper\Utils.py", line 480, in checkRewardPage
    wait.until(ec.presence_of_element_located(
  File "C:\Users\ismys\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
`

![image](https://github.com/Yudaotor/EsportsHelper/assets/12450341/000947f8-d508-4b3d-91b9-d1b4550b43c1)

**Comment by Yudaotor** [comment]
show the debug pic

**Comment by Sato-Isolated** [comment]
I'm sorry I don't have the screenshot anymore but it was the login page for the riot games account.

**Comment by Yudaotor** [comment]
> I'm sorry I don't have the screenshot anymore but it was the login page for the riot games account.

sounds like u didnt login successfully using cookies

**Comment by Sato-Isolated** [comment]
it's quite strange because the first hour I was well connected and then it disconnects me and this happens when I'm with the Headless option on true.

**Comment by Neblinio** [comment]
I have the same issue. Let me know if you need any logs or info
![error](https://github.com/Yudaotor/EsportsHelper/assets/171205/cf87172d-371a-422b-9d7f-75169c26eb95)

**Comment by Yudaotor** [comment]
> I have the same issue. Let me know if you need any logs or info ![error](https://private-user-images.githubusercontent.com/171205/301738305-cf87172d-371a-422b-9d7f-75169c26eb95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTI0MTEsIm5iZiI6MTcwNjg1MjExMSwicGF0aCI6Ii8xNzEyMDUvMzAxNzM4MzA1LWNmODcxNzJkLTM3MWEtNDIyYi05ZDdmLTc1MTY5YzI2ZWI5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNTM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzUzYjU1MDcwMTc3ODI4ZDVhNWUyMDc1ZmMwZjUxMGMxMmQwM2U3ZDFhZTlkZWJmYmY3MTcxYjBjNThmZjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KAKjn2hCLPLDfhA_tdNJl_FUSEugZqwmtObxYI9tACQ)

This is a display bug. In fact, you did not log in successfully.

**Comment by Neblinio** [comment]
Is there any solution? I'm running headless on Ubuntu, and since Riot implemented captcha my last possible way to login has been the cookies method. Recently, it has started failing too.

**Comment by Yudaotor** [comment]
> Is there any solution? I'm running headless on Ubuntu, and since Riot implemented captcha my last possible way to login has been the cookies method. Recently, it has started failing too.

reset cookies method maybe works

**Comment by NaniDaFuck** [comment]
same happens with me 

what is the right method to login successfully with cookies?

**Comment by Neblinio** [comment]
I have tried to completely reset cookies by deleting my "userDataDir". Then I installed xfce + google chrome and successfully login by manually resolving captcha + 2FA, and then grabbed the fresh new userDataDir (called "Default"). It didn't work. After a few seconds the process gets killed.

![image](https://github.com/Yudaotor/EsportsHelper/assets/171205/6cb76979-8371-4465-8261-ac703935bdab)

I also tried with an alt account that has no 2FA enabled, and I'm presented with the "please solve the captcha manually" (I'm running a headless ubuntu and couldn't solve it to test, but it should have worked fine)

**Comment by Yudaotor** [comment]
> I updated to the new EsportsHelper V2.3.2 version, and tried to completely reset cookies by deleting my "userDataDir". Then I installed xfce + google chrome and successfully login by manually resolving captcha + 2FA, and then grabbed the fresh new userDataDir (called "Default"). It didn't work. After a few seconds the process gets killed.
> 
> ![image](https://private-user-images.githubusercontent.com/171205/302036843-6cb76979-8371-4465-8261-ac703935bdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjY0NDYsIm5iZiI6MTcwNjk2NjE0NiwicGF0aCI6Ii8xNzEyMDUvMzAyMDM2ODQzLTZjYjc2OTc5LTgzNzEtNDQ2NS04MjYxLWFjNzAzOTM1YmRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMzE1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JlN2YyNzI5NjM5ZjlkMzM5N2RmMjBhM2FhMjBiZjIyMDc2NWI3ZGRlMmQxNWYwNmU2YWZhNmUyZjQwZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9BQq_p3argMynmO4aUmoG9rN2Ng77ygvEDfT_JJEHA8)
> 
> I also tried with an alt account that has no 2FA enabled, and I'm presented with the "please solve the captcha manually" (I'm running a headless ubuntu and couldn't solve it to test, but it should have worked fine)

when u login manually are u select "stay signed in"?

**Comment by Yudaotor** [comment]
> same happens with me
> 
> what is the right method to login successfully with cookies?

login to your account using a local chrome with selecting "stay signed in ", and configure the userdata path.

**Comment by Neblinio** [comment]
> when u login manually are u select "stay signed in"?

Yes I did.

By the way. I've been noticing something weird with lolesports website login process for the last year or longer. When I visit lolesports with my main Windows PC to watch games, sometimes I see a login button even though I always check "stay signed in". When I click it, I get instantly logged in without being asked for user & pass (my browser doesn't save any passwords, so cookies are being used). It happens a few times, and for example the next day you suddenly get remembered by lolesports, and are automatically logged in when you visit. And it stays like that for weeks or months.

Maybe this affects EsportsHelper's cookie login method? Just now I double checked my manual Chrome login from yesterday on Ubuntu, and when I visited lolesports it had the login button... but when I clicked it, it remembered me (using cookies, because my browser has 0 saved passwords).
