### ISSUE TITLE
Cannot start Docker

### ISSUE THREAD

**Issue by GioveWasTaken** [Yudaotor/EsportsHelper#108]
I got this logs:

2024-01-17 17:27:33 esportshelper  | [migrations] started
2024-01-17 17:27:33 esportshelper  | [migrations] no migrations found
2024-01-17 17:27:33 esportshelper  | ───────────────────────────────────────
2024-01-17 17:27:33 esportshelper  |   _____ __ __ _____ _____ _____ _____ 
2024-01-17 17:27:33 esportshelper  |  |     |  |  |   __|_   _|     |     |
2024-01-17 17:27:33 esportshelper  |  |   --|  |  |__   | | | |  |  | | | |
2024-01-17 17:27:33 esportshelper  |  |_____|_____|_____| |_| |_____|_|_|_|
2024-01-17 17:27:33 esportshelper  |        _____ __ __ _ __    ____  
2024-01-17 17:27:33 esportshelper  |       | __  |  |  | |  |  |    \ 
2024-01-17 17:27:33 esportshelper  |       | __ -|  |  | |  |__|  |  |
2024-01-17 17:27:33 esportshelper  |       |_____|_____|_|_____|____/ 
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  |   Based on images from linuxserver.io
2024-01-17 17:27:33 esportshelper  | ───────────────────────────────────────
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | To support LSIO projects visit:
2024-01-17 17:27:33 esportshelper  | https://www.linuxserver.io/donate/
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | ───────────────────────────────────────
2024-01-17 17:27:33 esportshelper  | GID/UID
2024-01-17 17:27:33 esportshelper  | ───────────────────────────────────────
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | User UID:    1000
2024-01-17 17:27:33 esportshelper  | User GID:    1000
2024-01-17 17:27:33 esportshelper  | ───────────────────────────────────────
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | [custom-init] No custom files found, skipping...
2024-01-17 17:27:33 esportshelper  | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | Xvnc KasmVNC 1.2.0 - built Dec  9 2023 18:40:46
2024-01-17 17:27:33 esportshelper  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
2024-01-17 17:27:33 esportshelper  | See http://kasmweb.com for information on KasmVNC.
2024-01-17 17:27:33 esportshelper  | Underlying X server release 12014000, The X.Org Foundation
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | [ls.io-init] done.
2024-01-17 17:27:33 esportshelper  | Obt-Message: Xinerama extension is not present on the server
2024-01-17 17:27:33 esportshelper  | /config/.config/openbox/menu.xml:5: parser error : Opening and ending tag mismatch: command line 5 and action
2024-01-17 17:27:33 esportshelper  | ion name="Execute"><command>/defaults/restart_esportshelper.sh/command></action>
2024-01-17 17:27:33 esportshelper  |                                                                                ^
2024-01-17 17:27:33 esportshelper  | /config/.config/openbox/menu.xml:5: parser error : Opening and ending tag mismatch: action line 5 and item
2024-01-17 17:27:33 esportshelper  | me="Execute"><command>/defaults/restart_esportshelper.sh/command></action></item
2024-01-17 17:27:33 esportshelper  |                                                                                ^
2024-01-17 17:27:33 esportshelper  | /config/.config/openbox/menu.xml:7: parser error : Opening and ending tag mismatch: item line 5 and menu
2024-01-17 17:27:33 esportshelper  |   </menu>
2024-01-17 17:27:33 esportshelper  |          ^
2024-01-17 17:27:33 esportshelper  | /config/.config/openbox/menu.xml:8: parser error : Opening and ending tag mismatch: menu line 3 and openbox_menu
2024-01-17 17:27:33 esportshelper  | </openbox_menu>
2024-01-17 17:27:33 esportshelper  |                ^
2024-01-17 17:27:33 esportshelper  | /config/.config/openbox/menu.xml:9: parser error : Premature end of data in tag openbox_menu line 2
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | ^
2024-01-17 17:27:33 esportshelper  | Fail: use zh_CN
2024-01-17 17:27:33 esportshelper  | 配置文件格式错误
2024-01-17 17:27:33 esportshelper  | 请检查是否存在中文字符以及冒号后面应该有一个空格
2024-01-17 17:27:33 esportshelper  | 配置路径如有单斜杠请改为双斜杠
2024-01-17 17:27:33 esportshelper  | Traceback (most recent call last):
2024-01-17 17:27:33 esportshelper  |   File "/esportshelper/EsportsHelper/Config.py", line 57, in __init__
2024-01-17 17:27:33 esportshelper  |     configFile = yaml.safe_load(f)
2024-01-17 17:27:33 esportshelper  |                  ^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
2024-01-17 17:27:33 esportshelper  |     return load(stream, SafeLoader)
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
2024-01-17 17:27:33 esportshelper  |     return loader.get_single_data()
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
2024-01-17 17:27:33 esportshelper  |     node = self.get_single_node()
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
2024-01-17 17:27:33 esportshelper  |     document = self.compose_document()
2024-01-17 17:27:33 esportshelper  |                ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
2024-01-17 17:27:33 esportshelper  |     node = self.compose_node(None, None)
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
2024-01-17 17:27:33 esportshelper  |     node = self.compose_mapping_node(anchor)
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
2024-01-17 17:27:33 esportshelper  |     item_value = self.compose_node(node, item_key)
2024-01-17 17:27:33 esportshelper  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 64, in compose_node
2024-01-17 17:27:33 esportshelper  |     if self.check_event(AliasEvent):
2024-01-17 17:27:33 esportshelper  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
2024-01-17 17:27:33 esportshelper  |     self.current_event = self.state()
2024-01-17 17:27:33 esportshelper  |                          ^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
2024-01-17 17:27:33 esportshelper  |     if not self.check_token(KeyToken, ValueToken, BlockEndToken):
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 116, in check_token
2024-01-17 17:27:33 esportshelper  |     self.fetch_more_tokens()
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
2024-01-17 17:27:33 esportshelper  |     return self.fetch_double()
2024-01-17 17:27:33 esportshelper  |            ^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 655, in fetch_double
2024-01-17 17:27:33 esportshelper  |     self.fetch_flow_scalar(style='"')
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
2024-01-17 17:27:33 esportshelper  |     self.tokens.append(self.scan_flow_scalar(style))
2024-01-17 17:27:33 esportshelper  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 1152, in scan_flow_scalar
2024-01-17 17:27:33 esportshelper  |     chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
2024-01-17 17:27:33 esportshelper  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 1223, in scan_flow_scalar_non_spaces
2024-01-17 17:27:33 esportshelper  |     raise ScannerError("while scanning a double-quoted scalar", start_mark,
2024-01-17 17:27:33 esportshelper  | yaml.scanner.ScannerError: while scanning a double-quoted scalar
2024-01-17 17:27:33 esportshelper  |   in "config.yaml", line 14, column 13
2024-01-17 17:27:33 esportshelper  | found unknown escape character 'G'
2024-01-17 17:27:33 esportshelper  |   in "config.yaml", line 14, column 31
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | During handling of the above exception, another exception occurred:
2024-01-17 17:27:33 esportshelper  | 
2024-01-17 17:27:33 esportshelper  | Traceback (most recent call last):
2024-01-17 17:27:33 esportshelper  |   File "/esportshelper/main.py", line 5, in <module>
2024-01-17 17:27:33 esportshelper  |     from EsportsHelper.Config import config
2024-01-17 17:27:33 esportshelper  |   File "/esportshelper/EsportsHelper/Config.py", line 298, in <module>
2024-01-17 17:27:33 esportshelper  |     config = Config(args.configPath)
2024-01-17 17:27:33 esportshelper  |              ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-17 17:27:33 esportshelper  |   File "/esportshelper/EsportsHelper/Config.py", line 107, in __init__
2024-01-17 17:27:33 esportshelper  |     input(_log("按回车键退出"))
2024-01-17 17:27:33 esportshelper  | EOFError: EOF when reading a line

What is happening? maybe python is too advanced?

**Comment by Yudaotor** [comment]
error in config format
