### ISSUE TITLE
軟體啓動后紅字報錯，重新安裝chrome也無法修復

### ISSUE THREAD

**Issue by qll1163** [Yudaotor/EsportsHelper#114]
2024-02-21 00:17:25,307 INFO: -----------------------------------------------------------------------
2024-02-21 00:17:25,307 INFO: ---------------------- Program started 2.3.2   -----------------------
2024-02-21 00:17:25,307 INFO: ---------------------- Open Source on github  ----------------------
2024-02-21 00:17:25,307 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-02-21 00:17:25,307 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-02-21 00:17:25,307 INFO: -----------------------------------------------------------------------
2024-02-21 00:17:25,500 ERROR: 从Github获取参数文件失败, 将尝试从Gitee获取
2024-02-21 00:17:32,206 INFO: 獲取參數檔案成功
2024-02-21 00:17:37,459 INFO: ====== WebDriver manager ======
2024-02-21 00:17:37,459 INFO: ====== WebDriver manager ======
2024-02-21 00:17:38,420 INFO: Get LATEST chromedriver version for google-chrome
2024-02-21 00:17:38,420 INFO: Get LATEST chromedriver version for google-chrome
2024-02-21 00:17:38,421 INFO: There is no [win64] chromedriver "121.0.6167.185" for browser google-chrome "121.0.6167.185" in cache
2024-02-21 00:17:38,421 INFO: Get LATEST chromedriver version for google-chrome
2024-02-21 00:17:40,481 INFO: WebDriver version 121.0.6167.184 selected
2024-02-21 00:17:40,487 INFO: Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/win32/chromedriver-win32.zip
2024-02-21 00:17:40,487 INFO: About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/win32/chromedriver-win32.zip
2024-02-21 00:17:40,490 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "socks.py", line 614, in _negotiate_SOCKS4
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socks.py", line 809, in connect
  File "socks.py", line 622, in _negotiate_SOCKS4
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\contrib\socks.py", line 96, in _new_conn
  File "socks.py", line 209, in create_connection
  File "socks.py", line 199, in create_connection
  File "socks.py", line 47, in wrapper
  File "socks.py", line 814, in connect
socks.GeneralProxyError: Socket error: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\contrib\socks.py", line 127, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F3720AEFD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chrome-for-testing-public/121.0.6167.184/win32/chromedriver-win32.zip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F3720AEFD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webdriver_manager\core\http.py", line 32, in get
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chrome-for-testing-public/121.0.6167.184/win32/chromedriver-win32.zip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001F3720AEFD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 34, in initWebdriver
  File "Webdriver.py", line 63, in createWebdriver
  File "webdriver_manager\chrome.py", line 40, in install
  File "webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
  File "webdriver_manager\core\download_manager.py", line 29, in download_file
  File "webdriver_manager\core\http.py", line 35, in get
requests.exceptions.ConnectionError: Could not reach host. Are you offline?

**Comment by qll1163** [comment]
可是我直接打開chrome上去看又完全沒有影響，我這樣看了幾天掉寶也是照常，就是有些晚上的場次看不了
