### ISSUE TITLE
Not starting: "Is Chrome installed?"

### ISSUE THREAD

**Issue by alexkanchev** [Yudaotor/EsportsHelper#130]
Preparing...
Is Google Chrome installed?
Is Google Chrome running?Please close it and try again.
If it still doesn't work, try reinstalling Google Chrome.

### **I've made sure Chrome is installed and the path is correct in the config.yaml. I've also tried reinstalling it. It used to work fine before, but now I can't seem to get it to boot up anymore. Here are the logs I'm getting:**

2024-05-10 03:48:12,626 INFO: -----------------------------------------------------------------------
2024-05-10 03:48:12,626 INFO: ---------------------- Program started 2.4.0   -----------------------
2024-05-10 03:48:12,626 INFO: ---------------------- Open Source on github  ----------------------
2024-05-10 03:48:12,626 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-05-10 03:48:12,626 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-05-10 03:48:12,626 INFO: -----------------------------------------------------------------------
2024-05-10 03:48:12,894 INFO: Parameter file successfully imported.
2024-05-10 03:48:13,380 INFO: ====== WebDriver manager ======
2024-05-10 03:48:17,752 INFO: Get LATEST chromedriver version for google-chrome
2024-05-10 03:48:17,812 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
2024-05-10 03:48:17,846 INFO: Driver downloading response is 200
2024-05-10 03:48:19,466 INFO: Get LATEST chromedriver version for google-chrome
2024-05-10 03:48:21,092 INFO: Get LATEST chromedriver version for google-chrome
2024-05-10 03:48:22,642 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\114.0.5735.90]
2024-05-10 03:48:24,697 INFO: Using default port 9222
2024-05-10 03:48:24,698 INFO: Preparing...
2024-05-10 03:48:24,712 INFO: patching driver executable .\driver\.wdm\drivers\chromedriver\win64\114.0.5735.90\chromedriver.exe
2024-05-10 03:49:26,924 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 38, in initWebdriver
  File "Webdriver.py", line 167, in createWebdriver
  File "undetected_chromedriver\__init__.py", line 441, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 80, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 704, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable

2024-05-10 03:49:39,138 INFO: Program exited.

**Comment by Yudaotor** [comment]
try other version's chrome?
