### ISSUE TITLE
LCK challenge转播源存在问题

### ISSUE THREAD

**Issue by Mashiro173** [Yudaotor/EsportsHelper#132]
不知道是否因为转播的播放器不能更改视频清晰度，一直尝试重新进入直播间
2024-06-10 14:33:42,090 ERROR: Twitch: 设置清晰度发生错误
2024-06-10 14:33:42,090 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "Twitch.py", line 68, in setTwitchQuality
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message: 

2024-06-10 14:33:42,103 INFO: LCK_CL 重试成功
2024-06-10 14:33:42,103 INFO: 
**************************************************
赛区: LCK_CL 清晰度: Auto
标题: FOX VS. HLE  0 - 1 (2/BESTOF 3)
**************************************************
2024-06-10 14:33:45,117 INFO: 下次检查在: 06-10 14:40:25
2024-06-10 14:33:45,117 INFO: ==================================================
2024-06-10 14:40:26,121 INFO: 开始检查...
2024-06-10 14:40:26,854 INFO: 检查赛区直播状态...
2024-06-10 14:40:27,533 INFO: 观看属地: 日本
2024-06-10 14:40:33,134 INFO: 获取日志数据
2024-06-10 14:40:33,135 INFO: 检查reward网站成功
2024-06-10 14:40:33,146 INFO: 程序启动时间: 2024-06-10 14:19:13 | 运行掉落总和(今日):0(1) | 生涯总掉落:202+0 | 总观看时长: 1271.27+0.18
2024-06-10 14:40:37,144 INFO: 1 个赛区正在直播中
2024-06-10 14:40:38,175 INFO: https://lolesports.com/live/lck_challengers_league/afchall https://lolesports.com/live/lck_challengers_league/lckcl
2024-06-10 14:40:38,175 WARNING: LCK_CL 进错直播间,正在重新进入
2024-06-10 14:40:42,491 INFO: LCK_CL 视频流关闭成功.
2024-06-10 14:41:12,908 ERROR: 未找到奖励标识
2024-06-10 14:41:12,921 INFO: LCK_CHALLENGERS_LEAGUE 观看异常 待重试
2024-06-10 14:42:00,684 ERROR: Twitch: 设置清晰度发生错误
2024-06-10 14:42:00,684 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "Twitch.py", line 68, in setTwitchQuality
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message: 

2024-06-10 14:42:31,028 ERROR: Twitch: 设置清晰度发生错误
2024-06-10 14:42:31,029 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "Twitch.py", line 68, in setTwitchQuality
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message: 

2024-06-10 14:42:31,043 INFO: LCK_CL 重试成功
2024-06-10 14:42:31,043 INFO: 
**************************************************
赛区: LCK_CL 清晰度: Auto
标题: FOX VS. HLE  1 - 1 (3/BESTOF 3)
**************************************************
2024-06-10 14:42:34,053 INFO: 下次检查在: 06-10 14:48:54
2024-06-10 14:42:34,054 INFO: ==================================================

**Comment by Yudaotor** [comment]
lck-cl只有Afreeca的源，这个源不支持。脚本只支持youtube和twitch

**Comment by Mashiro173** [comment]
不小心回错到邮件里去了。感谢解惑，不知能否改成Afreeca源不自动反复重进直播间，如果没空就算了，感谢作者开发
