### ISSUE TITLE
webdriver-manager版本問題

### ISSUE THREAD

**Issue by x9511022a** [Yudaotor/EsportsHelper#137]
```
2024-07-30 18:52:21,424 INFO: -----------------------------------------------------------------------
2024-07-30 18:52:21,424 INFO: ---------------------- Program started 2.4.0   -----------------------
2024-07-30 18:52:21,424 INFO: ---------------------- Open Source on github  ----------------------
2024-07-30 18:52:21,425 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-07-30 18:52:21,425 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-07-30 18:52:21,425 INFO: -----------------------------------------------------------------------
2024-07-30 18:52:21,429 INFO: 已配置觀看賽區,模式切換成默認模式.
2024-07-30 18:52:21,979 INFO: 獲取參數檔案成功
2024-07-30 18:52:22,977 INFO: ====== WebDriver manager ======
2024-07-30 18:52:23,611 INFO: Get LATEST chromedriver version for google-chrome
2024-07-30 18:52:23,612 INFO: Get LATEST chromedriver version for google-chrome
2024-07-30 18:52:23,612 INFO: There is no [win64] chromedriver "127.0.6533.73" for browser google-chrome "127.0.6533.73" in cache
2024-07-30 18:52:23,612 INFO: Get LATEST chromedriver version for google-chrome
2024-07-30 18:52:23,929 INFO: WebDriver version 127.0.6533.72 selected
2024-07-30 18:52:23,930 INFO: Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/win32/chromedriver-win32.zip
2024-07-30 18:52:23,930 INFO: About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/win32/chromedriver-win32.zip
2024-07-30 18:52:24,023 INFO: Driver downloading response is 200
2024-07-30 18:52:24,707 INFO: Get LATEST chromedriver version for google-chrome
2024-07-30 18:52:24,791 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\127.0.6533.73]
2024-07-30 18:52:26,801 INFO: 使用默認端口9222
2024-07-30 18:52:26,802 INFO: 正在準備中...
2024-07-30 18:52:26,802 INFO: patching driver executable .\driver\.wdm\drivers\chromedriver\win64\127.0.6533.73\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe
2024-07-30 18:52:26,803 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 38, in initWebdriver
  File "Webdriver.py", line 167, in createWebdriver
  File "undetected_chromedriver\__init__.py", line 246, in __init__
  File "undetected_chromedriver\patcher.py", line 99, in auto
  File "undetected_chromedriver\patcher.py", line 217, in patch_exe
FileNotFoundError: [Errno 2] No such file or directory: '.\\driver\\.wdm\\drivers\\chromedriver\\win64\\127.0.6533.73\\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe'
```
經過google之後，好像是要[更新webdriver-manage版本](https://stackoverflow.com/questions/78789819/issue-with-selenium-and-webdriver/78796998)
我更新之後重新打包exe可以正常執行

**Comment by DRCX** [comment]
挂箱子出问题因为这玩意又更新了...每次更新都要修改一次....
![image](https://github.com/user-attachments/assets/2994914d-546a-49e6-b460-f757a4fee6f7)

**Comment by DRCX** [comment]
google chrome btea是130版本。可以直接加载倒是不受影响的
![image](https://github.com/user-attachments/assets/0969079d-e0b9-4707-b1b2-757d2775ef8c)

**Comment by DRCX** [comment]
还经测试，程序并不支持131版本的Chrome Dev，提示找不到目录
