### ISSUE TITLE
i keep gettings this error

### ISSUE THREAD

**Issue by NaniDaFuck** [Yudaotor/EsportsHelper#139]
![image](https://github.com/user-attachments/assets/e660d5bc-b542-4bdb-ba99-53e90f813def)

**Comment by ReformedDoge** [comment]
Your Chrome driver failed to initialize. Could you share the errors from the latest log file? in  _..\logs\programs_

**Comment by NaniDaFuck** [comment]
[EsportsHelperV2.4.0_08.12_03-03.log](https://github.com/user-attachments/files/16576490/EsportsHelperV2.4.0_08.12_03-03.log)

**Comment by NaniDaFuck** [comment]
2024-08-12 03:03:36,213 INFO: -----------------------------------------------------------------------
2024-08-12 03:03:36,214 INFO: ---------------------- Program started 2.4.0   -----------------------
2024-08-12 03:03:36,214 INFO: ---------------------- Open Source on github  ----------------------
2024-08-12 03:03:36,214 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-08-12 03:03:36,215 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-08-12 03:03:36,215 INFO: -----------------------------------------------------------------------
2024-08-12 03:03:36,673 INFO: Parameter file successfully imported.
2024-08-12 03:03:37,688 INFO: ====== WebDriver manager ======
2024-08-12 03:03:38,801 INFO: Get LATEST chromedriver version for google-chrome
2024-08-12 03:03:38,801 INFO: Get LATEST chromedriver version for google-chrome
2024-08-12 03:03:38,802 INFO: There is no [win64] chromedriver "127.0.6533.100" for browser google-chrome "127.0.6533.100" in cache
2024-08-12 03:03:38,802 INFO: Get LATEST chromedriver version for google-chrome
2024-08-12 03:03:39,089 INFO: WebDriver version 127.0.6533.99 selected
2024-08-12 03:03:39,093 INFO: Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/win32/chromedriver-win32.zip
2024-08-12 03:03:39,093 INFO: About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/win32/chromedriver-win32.zip
2024-08-12 03:03:39,270 INFO: Driver downloading response is 200
2024-08-12 03:03:41,367 INFO: Get LATEST chromedriver version for google-chrome
2024-08-12 03:03:41,536 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\127.0.6533.100]
2024-08-12 03:03:43,571 INFO: Using default port 9222
2024-08-12 03:03:43,575 INFO: Preparing...
2024-08-12 03:03:43,578 INFO: patching driver executable .\driver\.wdm\drivers\chromedriver\win64\127.0.6533.100\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe
2024-08-12 03:03:43,583 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 38, in initWebdriver
  File "Webdriver.py", line 167, in createWebdriver
  File "undetected_chromedriver\__init__.py", line 246, in __init__
  File "undetected_chromedriver\patcher.py", line 99, in auto
  File "undetected_chromedriver\patcher.py", line 217, in patch_exe
FileNotFoundError: [Errno 2] No such file or directory: '.\\driver\\.wdm\\drivers\\chromedriver\\win64\\127.0.6533.100\\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe'

**Comment by ReformedDoge** [comment]
I believe this issue is related to [Issue #137](https://github.com/Yudaotor/EsportsHelper/issues/137).

To resolve this, please follow these steps:

1. Navigate to the following path: .\driver\.wdm\drivers\chromedriver\win64\127.0.6533.100\chromedriver-win32
2. Rename the file chromedriver.exe to THIRD_PARTY_NOTICES.chromedriver.exe

_Please let me know if this solution works for you._

> Relevant Information:
> This issue is likely caused by an older version of webdriver_manager. Upgrading to the latest version should resolve it. For more details: [webdriver_manager Issue #663](https://github.com/SergeyPirogov/webdriver_manager/issues/663).

**Comment by NaniDaFuck** [comment]
that fixed it thanks <3

**Comment by NaniDaFuck** [comment]
that fixed it thank you

**Comment by NaniDaFuck** [comment]
is there is no permeant fix for this issue 
i have to change name every time there is update :(

**Comment by ReformedDoge** [comment]
@NaniDaFuck

Based on the issue I linked earlier, I assume that updating webdriver_manager to version **4.0.2** in the requirements.txt file might resolve the problem. After updating the file, try running the following command in the root directory:
`python -m pip install -r requirements.txt
`

This should help, but please let me know if the issue persists.

**Comment by x1207349263** [comment]
> @NaniDaFuck
> 
> Based on the issue I linked earlier, I assume that updating webdriver_manager to version **4.0.2** in the requirements.txt file might resolve the problem. After updating the file, try running the following command in the root directory: `python -m pip install -r requirements.txt `
> 
> This should help, but please let me know if the issue persists.

thank you.i also fixed this issue by following your steps
