### ISSUE TITLE
no fire direction

### ISSUE THREAD

**Issue by MehmetCanWT** [Yudaotor/EsportsHelper#143]
![resim](https://github.com/user-attachments/assets/388def71-49ae-4ab5-8770-aa5f9c06b7bc)

im getting this error itried driver\.wdm\drivers\chromedriver\win64\129.0.6668.71\chromedriver-win32  rename chromedriver to THIRD_PARTY_NOTICES.chromedriver.exe but thats not working

**Comment by FriedGenera** [comment]
Did you try - https://github.com/Yudaotor/EsportsHelper/issues/139#issuecomment-2295376199 ?

**Comment by MehmetCanWT** [comment]
> Did you try - [#139 (comment)](https://github.com/Yudaotor/EsportsHelper/issues/139#issuecomment-2295376199) ?

yeah i tried that too

**Comment by MehmetCanWT** [comment]
i fixed the driver problem but now its giving this

2024-09-27 15:27:53,149 INFO: -----------------------------------------------------------------------
2024-09-27 15:27:53,149 INFO: ---------------------- Program started 2.4.0   -----------------------
2024-09-27 15:27:53,149 INFO: ---------------------- Open Source on github  ----------------------
2024-09-27 15:27:53,149 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-09-27 15:27:53,149 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-09-27 15:27:53,149 INFO: -----------------------------------------------------------------------
2024-09-27 15:27:53,149 INFO: The viewing league has been configured, and the mode is switched to the normal mode.
2024-09-27 15:27:53,508 INFO: Parameter file successfully imported.
2024-09-27 15:27:54,118 INFO: ====== WebDriver manager ======
2024-09-27 15:27:55,133 INFO: Get LATEST chromedriver version for google-chrome
2024-09-27 15:27:55,133 INFO: Get LATEST chromedriver version for google-chrome
2024-09-27 15:27:55,133 INFO: There is no [win64] chromedriver "129.0.6668.71" for browser google-chrome "129.0.6668.71" in cache
2024-09-27 15:27:55,133 INFO: Get LATEST chromedriver version for google-chrome
2024-09-27 15:27:55,212 INFO: WebDriver version 129.0.6668.70 selected
2024-09-27 15:27:55,212 INFO: Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/win32/chromedriver-win32.zip
2024-09-27 15:27:55,212 INFO: About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/win32/chromedriver-win32.zip
2024-09-27 15:27:55,258 INFO: Driver downloading response is 200
2024-09-27 15:27:55,352 INFO: Get LATEST chromedriver version for google-chrome
2024-09-27 15:27:55,883 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\129.0.6668.71]
2024-09-27 15:27:57,915 INFO: Using default port 9222
2024-09-27 15:27:57,915 INFO: Preparing...
2024-09-27 15:28:59,083 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 38, in initWebdriver
  File "Webdriver.py", line 167, in createWebdriver
  File "undetected_chromedriver\__init__.py", line 441, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 80, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 704, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable
