### ISSUE TITLE
该目录下文件查找失败!请检查路径

### ISSUE THREAD

**Issue by TheOnlyIkun** [Yudaotor/EsportsHelper#146]
2024-10-05 00:55:21,977 INFO: -----------------------------------------------------------------------
2024-10-05 00:55:21,977 INFO: ---------------------- Program started 2.4.0   -----------------------
2024-10-05 00:55:21,978 INFO: ---------------------- Open Source on github  ----------------------
2024-10-05 00:55:21,978 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2024-10-05 00:55:21,978 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2024-10-05 00:55:21,978 INFO: -----------------------------------------------------------------------
2024-10-05 00:55:22,402 INFO: 获取参数文件成功
2024-10-05 00:55:23,893 INFO: ====== WebDriver manager ======
2024-10-05 00:55:24,856 INFO: Get LATEST chromedriver version for google-chrome
2024-10-05 00:55:24,856 INFO: Get LATEST chromedriver version for google-chrome
2024-10-05 00:55:24,857 INFO: There is no [win64] chromedriver "129.0.6668.90" for browser google-chrome "129.0.6668.90" in cache
2024-10-05 00:55:24,857 INFO: Get LATEST chromedriver version for google-chrome
2024-10-05 00:55:25,327 INFO: WebDriver version 129.0.6668.89 selected
2024-10-05 00:55:25,329 INFO: Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.89/win32/chromedriver-win32.zip
2024-10-05 00:55:25,330 INFO: About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.89/win32/chromedriver-win32.zip
2024-10-05 00:55:25,605 INFO: Driver downloading response is 200
2024-10-05 00:55:26,272 INFO: Get LATEST chromedriver version for google-chrome
2024-10-05 00:55:26,406 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\129.0.6668.90]
2024-10-05 00:55:28,427 INFO: 使用默认端口9222
2024-10-05 00:55:28,430 INFO: 正在准备中...
2024-10-05 00:55:28,430 INFO: patching driver executable .\driver\.wdm\drivers\chromedriver\win64\129.0.6668.90\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe
2024-10-05 00:55:28,431 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 38, in initWebdriver
  File "Webdriver.py", line 167, in createWebdriver
  File "undetected_chromedriver\__init__.py", line 246, in __init__
  File "undetected_chromedriver\patcher.py", line 99, in auto
  File "undetected_chromedriver\patcher.py", line 217, in patch_exe
FileNotFoundError: [Errno 2] No such file or directory: '.\\driver\\.wdm\\drivers\\chromedriver\\win64\\129.0.6668.90\\chromedriver-win32/THIRD_PARTY_NOTICES.chromedriver.exe'

**Comment by TheOnlyIkun** [comment]
一直是这样，，，，求救啊大佬们

**Comment by DRCX** [comment]
same as https://github.com/Yudaotor/EsportsHelper/issues/139
