### ISSUE TITLE
selenium.common.exceptions.TimeoutException

### ISSUE THREAD

**Issue by LeeG4ng** [Yudaotor/EsportsHelper#3]
Youtube貌似会必现selenium.common.exceptions.TimeoutException，我在本地开代理、AWS EC2 HK上都是这个情况，应该不是网络的问题吧

```
Traceback (most recent call last):
  File "Youtube.py", line 17, in setYoutubeQuality
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x00C3DCE3]
        (No symbol) [0x00BD39D1]
        (No symbol) [0x00AE4DA8]
        (No symbol) [0x00B1019F]
        (No symbol) [0x00B103AB]
        (No symbol) [0x00B3EE62]
        (No symbol) [0x00B2AF14]
        (No symbol) [0x00B3D57C]
        (No symbol) [0x00B2ACC6]
        (No symbol) [0x00B06F68]
        (No symbol) [0x00B080CD]
        GetHandleVerifier [0x00EB3832+2506274]
        GetHandleVerifier [0x00EE9794+2727300]
        GetHandleVerifier [0x00EEE36C+2746716]
        GetHandleVerifier [0x00CE6690+617600]
        (No symbol) [0x00BDC712]
        (No symbol) [0x00BE1FF8]
        (No symbol) [0x00BE20DB]
        (No symbol) [0x00BEC63B]
        BaseThreadInitThunk [0x76BA6A39+25]
        RtlGetFullPathName_UEx [0x77917C9D+173]
        RtlGetFullPathName_UEx [0x77917C6B+123]
```

**Comment by Yudaotor** [comment]
我这里youtube源是没有报错的,我再看看

**Comment by Yudaotor** [comment]
应该是因为对应的赛区链接没有导入导致的问题,twitch源识别成youtube了,导入后即可解决
