### ISSUE TITLE
[feature request] 希望增加推送信息类型的选择

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#33]
异常信息推送有点太频繁了。。。作为需要用梯子的网络偶尔抽风挺正常，希望能在config.yaml里加一个参数来控制推送信息的类型，例如：
`pushinfotype`: "drop only/warning/informative"

![image](https://user-images.githubusercontent.com/57741549/233258225-45577bc2-3b13-4f08-ba5c-8e33fd20d83f.png)
以下是错误信息：
```
2023-04-20 12:21:48,298 ERROR: 发生错误
2023-04-20 12:21:48,301 ERROR: Traceback (most recent call last):
  File "/home/z/EsportsHelper/EsportsHelper/Match.py", line 87, in watchMatches
    self.driver.switch_to.window(self.rewardWindow)
  File "/home/z/.local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 130, in window
    self._w3c_window(window_name)
  File "/home/z/.local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 138, in _w3c_window
    send_handle(window_name)
  File "/home/z/.local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 134, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {"handle": h})
  File "/home/z/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/z/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=112.0.5615.121)
Stacktrace:
#0 0x5571e9cd0fe3 <unknown>
#1 0x5571e9a0fd36 <unknown>
#2 0x5571e99f7948 <unknown>
#3 0x5571e99f8db2 <unknown>
#4 0x5571e99f8d04 <unknown>
#5 0x5571e99e951e <unknown>
#6 0x5571e99ea176 <unknown>
#7 0x5571e9a79a5b <unknown>
#8 0x5571e9a6d888 <unknown>
#9 0x5571e9a4003a <unknown>
#10 0x5571e9a4117e <unknown>
#11 0x5571e9c92dbd <unknown>
#12 0x5571e9c96c6c <unknown>
#13 0x5571e9ca04b0 <unknown>
#14 0x5571e9c97d63 <unknown>
#15 0x5571e9c6ac35 <unknown>
#16 0x5571e9cbb138 <unknown>
#17 0x5571e9cbb2c7 <unknown>
#18 0x5571e9cc9093 <unknown>
#19 0x7fd7d438fb43 <unknown>


2023-04-20 12:21:48,821 INFO: 异常提醒成功
2023-04-20 12:21:51,846 ERROR: 发生错误
2023-04-20 12:21:51,846 INFO: ------Quit------
2023-04-20 12:21:55,350 ERROR: Exit
2023-04-20 12:21:55,350 INFO: ------Quit------
2023-04-20 12:21:55,351 INFO: ensuring close
```

**Comment by Yudaotor** [comment]
加提醒類型這個主意可以接受，但至於你他提到的頻繁這個問題，最起碼我自己使用是幾乎沒有什麼報錯的

**Comment by Yudaotor** [comment]
下版本将支持推送信息筛选

**Comment by Yudaotor** [comment]
已支持
