### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Jokiblack** [Yudaotor/EsportsHelper#45]
waiting MSI error
2023-05-02 09:59:41,283 ERROR: Traceback (most recent call last):
  File "Match.py", line 203, in watchMatches
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message: 

2023-05-02 09:59:44,463 ERROR: An error has occurred.
2023-05-02 09:59:44,463 INFO: ------Quit------
2023-05-02 09:59:47,967 ERROR: Exit
2023-05-02 09:59:47,967 INFO: ------Quit------
2023-05-02 09:59:47,967 INFO: ensuring close

**Comment by Yudaotor** [comment]
It may happen in the case of headless: False, you can try headless: True, so that the problem does not seem to occur
