### ISSUE TITLE
统计掉落失败

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#46]
统计掉落失败，推测是因为出了MSI限定表情，直接到背包里而导致的BUG。
![image](https://user-images.githubusercontent.com/57741549/236225390-2dc0ef02-9b4d-4f45-aded-7f17d628df36.png)

log:
```
2023-05-04 21:04:50,987 INFO: 开始检查...
2023-05-04 21:04:50,991 INFO: 检查赛区直播状态...
2023-05-04 21:04:56,868 ERROR: 统计掉落失败
2023-05-04 21:04:56,889 ERROR: Traceback (most recent call last):
  File "/home/z/EsportsHelper/EsportsHelper/Match.py", line 596, in countDrops
    self.driver.find_element(
  File "/home/z/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/z/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 404, in _execute
    return self._parent.execute(command, params)
  File "/home/z/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/z/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="name">...</div> is not clickable at point (160, 41). Other element would receive the click: <div class="_1HHPg3wFUKgbozh3A2CcVl riotbar-header ">...</div>
  (Session info: chrome=112.0.5615.121)
Stacktrace:
#0 0x5568c007bfe3 <unknown>
#1 0x5568bfdbad36 <unknown>
#2 0x5568bfdfeaef <unknown>
#3 0x5568bfdfca31 <unknown>
#4 0x5568bfdfa2de <unknown>
#5 0x5568bfdf9358 <unknown>
#6 0x5568bfded0c5 <unknown>
#7 0x5568bfe188c2 <unknown>
#8 0x5568bfdec943 <unknown>
#9 0x5568bfe18a8e <unknown>
#10 0x5568bfe31232 <unknown>
#11 0x5568bfe18693 <unknown>
#12 0x5568bfdeb03a <unknown>
#13 0x5568bfdec17e <unknown>
#14 0x5568c003ddbd <unknown>
#15 0x5568c0041c6c <unknown>
#16 0x5568c004b4b0 <unknown>
#17 0x5568c0042d63 <unknown>
#18 0x5568c0015c35 <unknown>
#19 0x5568c0066138 <unknown>
#20 0x5568c00662c7 <unknown>
#21 0x5568c0074093 <unknown>
#22 0x7f4a3001bb43 <unknown>


2023-05-04 21:04:58,967 INFO: 1 个赛区正在直播中
2023-05-04 21:05:00,036 INFO: msi 正常观看 可获取奖励 BLG vs. GG  88630 人观看
2023-05-04 21:05:03,142 INFO: 下次检查在: 05-04 21:15:33
2023-05-04 21:05:03,142 INFO: ==================================================
```

**Comment by Yudaotor** [comment]
看起来好像不是这个原因,是因为找不到MSI对应的元素.我猜测是因为网络问题导致没及时刷新出来
