### ISSUE TITLE
新的依赖有问题,回退至之前版本requirements.txt解决

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#47]
环境：WSL2 Ubuntu22+
```
2023-06-08 14:40:25,544 INFO: -----------------------------------------------------------------------
2023-06-08 14:40:25,544 INFO: ---------------------- Program started 1.6.2   -----------------------
2023-06-08 14:40:25,544 INFO: ---------------------- Open Source on github  ----------------------
2023-06-08 14:40:25,544 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2023-06-08 14:40:25,544 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2023-06-08 14:40:25,544 INFO: -----------------------------------------------------------------------
2023-06-08 14:40:26,774 INFO: 获取参数文件成功
2023-06-08 14:40:28,048 INFO: ====== WebDriver manager ======
2023-06-08 14:40:28,049 INFO: ====== WebDriver manager ======
2023-06-08 14:40:28,049 INFO: 正在准备中...
2023-06-08 14:40:28,071 INFO: Get LATEST chromedriver version for google-chrome 114.0.5735
2023-06-08 14:40:29,450 INFO: There is no [linux64] chromedriver for browser 114.0.5735 in cache
2023-06-08 14:40:29,450 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2023-06-08 14:40:35,957 INFO: Driver has been saved in cache [driver/.wdm/drivers/chromedriver/linux64/114.0.5735]
2023-06-08 14:40:35,964 INFO: patching driver executable driver/.wdm/drivers/chromedriver/linux64/114.0.5735/chromedriver
2023-06-08 14:40:36,013 ERROR: Traceback (most recent call last):
  File "/home/z/EsportsHelper/main.py", line 31, in init
    driver = Webdriver().createWebdriver()
  File "/home/z/EsportsHelper/EsportsHelper/Webdriver.py", line 62, in createWebdriver
    return uc.Chrome(**{k: v for k, v in kwargs.items() if v})
  File "/home/z/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

2023-06-08 14:40:38,150 INFO: 程序退出
2023-06-08 14:40:39,835 INFO: -----------------------------------------------------------------------
2023-06-08 14:40:39,835 INFO: ---------------------- Program started 1.6.2   -----------------------
2023-06-08 14:40:39,835 INFO: ---------------------- Open Source on github  ----------------------
2023-06-08 14:40:39,835 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2023-06-08 14:40:39,835 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2023-06-08 14:40:39,835 INFO: -----------------------------------------------------------------------
2023-06-08 14:40:41,223 INFO: 获取参数文件成功
2023-06-08 14:40:42,605 INFO: ====== WebDriver manager ======
2023-06-08 14:40:42,605 INFO: ====== WebDriver manager ======
2023-06-08 14:40:42,605 INFO: 正在准备中...
2023-06-08 14:40:42,627 INFO: Get LATEST chromedriver version for google-chrome 114.0.5735
2023-06-08 14:40:43,836 INFO: Driver [driver/.wdm/drivers/chromedriver/linux64/114.0.5735/chromedriver] found in cache
2023-06-08 14:40:43,940 ERROR: Traceback (most recent call last):
  File "/home/z/EsportsHelper/main.py", line 31, in init
    driver = Webdriver().createWebdriver()
  File "/home/z/EsportsHelper/EsportsHelper/Webdriver.py", line 62, in createWebdriver
    return uc.Chrome(**{k: v for k, v in kwargs.items() if v})
  File "/home/z/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

2023-06-08 14:40:46,251 INFO: 程序退出
```

**Comment by Yudaotor** [comment]
opencc没有使用了,所以移除了.还有的改动就是selenium的版本,难道是新版本用不了吗
