### ISSUE TITLE
按Linux步骤运行最后一步报错该怎么办

### ISSUE THREAD

**Issue by ppppppgod** [Yudaotor/EsportsHelper#83]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from EsportsHelper.Config import config
  File "/home/roott/桌面/EsportsHelper2/EsportsHelper/Config.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by Yudaotor** [comment]
环境没配好 把requirement.txt里的都配好

**Comment by ppppppgod** [comment]
> 环境没配好就把requirement.txt里的都配好

好的多谢大佬，刚发现pipenv install -r requirements.txt这条报错了Missing dependencies for SOCKS support.我看看怎么解决
