### ISSUE TITLE
°D° Youtube 清晰度设置失败

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#9]
环境：WSL2 Ubuntu 22.04 lts  X86_64 WIN11    headless mode

```
Traceback (most recent call last):
  File "/home/z/EsportsHelper/EsportsHelper/Youtube.py", line 17, in setYoutubeQuality
    wait.until(ec.frame_to_be_available_and_switch_to_it((By.CSS_SELECTOR, "iframe[id=video-player-youtube]")))
  File "/home/z/anaconda3/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55c863a92243 <unknown>
#1 0x55c8638567a6 <unknown>
#2 0x55c86389364d <unknown>
#3 0x55c863893761 <unknown>
#4 0x55c8638ceda4 <unknown>
#5 0x55c8638b40ad <unknown>
#6 0x55c8638cc932 <unknown>
#7 0x55c8638b3e53 <unknown>
#8 0x55c8638869ea <unknown>
#9 0x55c863887b2e <unknown>
#10 0x55c863ae6d5e <unknown>
#11 0x55c863aeaa80 <unknown>
#12 0x55c863acc8b0 <unknown>
#13 0x55c863aebb63 <unknown>
#14 0x55c863abdf75 <unknown>
#15 0x55c863b0e998 <unknown>
#16 0x55c863b0eb27 <unknown>
#17 0x55c863b29c23 <unknown>
#18 0x7f69ad343b43 <unknown>

°D° Youtube 清晰度设置失败
√√√√√ nlc 正常观看 √√√√√
```

**Comment by Yudaotor** [comment]
现在应该已经好了，你重启软件试试。之前是因为这两个赛区我信息没导入，twitch误使用了youtube的设置
