### ISSUE TITLE
is it safe

### ISSUE THREAD

**Issue by MehmetCanWT** [Yudaotor/EsportsHelper#91]
i used capsule farmer befire and get warning f4om lolesports is it safe to use this

![Screenshot_20231012-095326_Chrome](https://github.com/Yudaotor/EsportsHelper/assets/52177084/d71a192c-3850-4bad-980a-5dd9576e0cf3)

**Comment by Yudaotor** [comment]
safe,use safe mode is ok

**Comment by MehmetCanWT** [comment]
i wanna use on linux server is it useable on terminal only

**Comment by MehmetCanWT** [comment]
or am i need visual

**Comment by MehmetCanWT** [comment]
![image](https://github.com/Yudaotor/EsportsHelper/assets/52177084/a5f4b38f-de78-41e9-b105-1fc846b337e1)

im getting this error

**Comment by MehmetCanWT** [comment]
2023-10-12 11:22:20,566 INFO: -----------------------------------------------------------------------
2023-10-12 11:22:20,566 INFO: ---------------------- Program started 2.3.1   -----------------------
2023-10-12 11:22:20,566 INFO: ---------------------- Open Source on github  ----------------------
2023-10-12 11:22:20,566 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2023-10-12 11:22:20,566 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2023-10-12 11:22:20,566 INFO: -----------------------------------------------------------------------
2023-10-12 11:22:20,568 ERROR: 配置文件格式错误
2023-10-12 11:22:20,568 ERROR: 请检查是否存在中文字符以及冒号后面应该有一个空格
2023-10-12 11:22:20,568 ERROR: 配置路径如有单斜杠请改为双斜杠
2023-10-12 11:22:20,569 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "Config.py", line 57, in __init__
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 81, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 64, in compose_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 449, in parse_block_mapping_value
  File "yaml\scanner.py", line 116, in check_token
  File "yaml\scanner.py", line 251, in fetch_more_tokens
  File "yaml\scanner.py", line 655, in fetch_double
  File "yaml\scanner.py", line 666, in fetch_flow_scalar
  File "yaml\scanner.py", line 1149, in scan_flow_scalar
  File "yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "config.yaml", line 14, column 14
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "config.yaml", line 14, column 19

**Comment by Yudaotor** [comment]
show ur config.yaml file.something wrong

**Comment by MehmetCanWT** [comment]
logs shows me 14 19 its user data section

**Comment by MehmetCanWT** [comment]
![image](https://github.com/Yudaotor/EsportsHelper/assets/52177084/c36eed93-1b8e-4f0f-804e-8409d1a37db3)

**Comment by MehmetCanWT** [comment]
i fix it i need put \\ instead of \ to chrome dir and userdata dir

**Comment by MehmetCanWT** [comment]
![image](https://github.com/Yudaotor/EsportsHelper/assets/52177084/aa6b0429-b23a-4a14-a70b-d326cef16113)

now im gettings this error

**Comment by Yudaotor** [comment]
> ![image](https://user-images.githubusercontent.com/52177084/274545664-aa6b0429-b23a-4a14-a70b-d326cef16113.png)
> 
> now im gettings this error


Have you logged in manually and need to remember your login status?

**Comment by MehmetCanWT** [comment]
it fix it thanks

**Comment by MehmetCanWT** [comment]
![image](https://github.com/Yudaotor/EsportsHelper/assets/52177084/378403b2-43cf-4328-92e1-63ff34914f4a)

i tried on ubuntu and giving this error

**Comment by HakkaYoro** [comment]
> ![image](https://user-images.githubusercontent.com/52177084/274695817-378403b2-43cf-4328-92e1-63ff34914f4a.png)
> 
> i tried on ubuntu and giving this error

on config file write//change
`headless: False`
and try again, in my case it was a captcha that the login page threw to me
