### ISSUE TITLE
Program crashes in Headless more

### ISSUE THREAD

**Issue by GioveWasTaken** [Yudaotor/EsportsHelper#99]
`2023-11-03 08:54:37,161 INFO: -----------------------------------------------------------------------
2023-11-03 08:54:37,161 INFO: ---------------------- Program started 2.3.1   -----------------------
2023-11-03 08:54:37,161 INFO: ---------------------- Open Source on github  ----------------------
2023-11-03 08:54:37,161 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
2023-11-03 08:54:37,162 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
2023-11-03 08:54:37,162 INFO: -----------------------------------------------------------------------
2023-11-03 08:54:37,470 INFO: Parameter file successfully imported.
2023-11-03 08:54:40,675 INFO: ====== WebDriver manager ======
2023-11-03 08:54:40,675 INFO: ====== WebDriver manager ======
2023-11-03 08:54:41,676 INFO: Get LATEST chromedriver version for google-chrome
2023-11-03 08:54:41,676 INFO: Get LATEST chromedriver version for google-chrome
2023-11-03 08:54:41,677 INFO: There is no [win64] chromedriver "119.0.6045.105" for browser google-chrome "119.0.6045.105" in cache
2023-11-03 08:54:41,677 INFO: Get LATEST chromedriver version for google-chrome
2023-11-03 08:54:41,758 INFO: WebDriver version 119.0.6045.105 selected
2023-11-03 08:54:41,759 INFO: Modern chrome version https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/win32/chromedriver-win32.zip
2023-11-03 08:54:41,759 INFO: About to download new driver from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/win32/chromedriver-win32.zip
2023-11-03 08:54:42,101 INFO: Driver downloading response is 200
2023-11-03 08:54:42,822 INFO: Get LATEST chromedriver version for google-chrome
2023-11-03 08:54:42,959 INFO: Driver has been saved in cache [.\driver\.wdm\drivers\chromedriver\win64\119.0.6045.105]
2023-11-03 08:54:42,962 INFO: Preparing...
2023-11-03 08:54:43,055 INFO: patching driver executable .\driver\.wdm\drivers\chromedriver\win64\119.0.6045.105\chromedriver-win32/chromedriver.exe
2023-11-03 08:54:43,905 INFO: setting properties for headless
2023-11-03 08:54:51,084 INFO: Web language switched successfully.
2023-11-03 08:54:52,051 INFO: Accept cookies
2023-11-03 08:54:58,363 INFO: <G2> Logging in...
2023-11-03 08:55:05,094 INFO: Account credentials inserted...
2023-11-03 08:55:36,952 ERROR: ++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "LoginHandler.py", line 70, in automaticLogIn
  File "selenium\webdriver\support\wait.py", line 95, in until
selenium.common.exceptions.TimeoutException: Message: 

2023-11-03 08:55:38,143 ERROR: An exception occurred, login failed.
2023-11-03 08:55:38,144 INFO: Program exited. `
`

Hello there! This is my log when i try to run the program in headless mode. Suggestions?

**Comment by redr00t** [comment]
https://github.com/Yudaotor/EsportsHelper/issues/81

It's likely because Riot Games has implemented a captcha system when logging into your account. The bot can't complete that captcha, so you'll need to do it manually, and running the browser in "headless" mode is not an option.
